# -*- coding: utf-8 -*-
"""Task1: Variables and Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1737YRYWHgRAhQe9VbqZ1e2PVIb02pRiP

Answer each question by doing some operations with Python. Put conclusion in the comments

1.1 For the following variables, use the function type() from Python to check the data type for the variables.
"""

x1 = 1.1
x2 = "Monday"
x3 = "1.1"
x4 = True
x5 = "True"
x6 = -1

# Check data types
print("Data types:")
print(f"x1 = {x1}, type: {type(x1)}")  # float
print(f"x2 = {x2}, type: {type(x2)}")  # str
print(f"x3 = {x3}, type: {type(x3)}")  # str
print(f"x4 = {x4}, type: {type(x4)}")  # bool
print(f"x5 = {x5}, type: {type(x5)}")  # str
print(f"x6 = {x6}, type: {type(x6)}")  # int

"""1.2 What is the difference between variables x1 and x3?"""

# type(x1)
print(f"\n1.2 Difference between x1 and x3:")
print(f"x1 = {x1}, type: {type(x1)}")  # float: 1.1
print(f"x3 = {x3}, type: {type(x3)}")  # string: "1.1"
# Conclusion: x1 is a float (numeric) while x3 is a string (text)

"""1.3 What happens if you subtract x3 from x1?"""

try:
    result = x1 - x3
    print(f"\n1.3 x1 - x3 = {result}")
except TypeError as e:
    print(f"\n1.3 Error: {e}")
    print("Cannot subtract string from float - TypeError occurs")
# Conclusion: TypeError - cannot perform arithmetic between float and string

"""1.4 What is the difference between variables x4 and x5?"""

print(f"\n1.4 Difference between x4 and x5:")
print(f"x4 = {x4}, type: {type(x4)}")  # bool: True
print(f"x5 = {x5}, type: {type(x5)}")  # string: "True"
# Conclusion: x4 is a boolean (True) while x5 is a string ("True")

"""1.5 What happens if you subtract x5 from x4?"""

try:
    result = x4 - x5
    print(f"\n1.5 x4 - x5 = {result}")
except TypeError as e:
    print(f"\n1.5 Error: {e}")
    print("Cannot subtract string from boolean - TypeError occurs")
# Conclusion: TypeError - cannot perform arithmetic between boolean and string

"""2.1 To gather input from the user, we can use the function input(message), where "message" is a meaningful message of type str and will be displayed to the user."""

# Get user input
x1 = input("Enter first number: ")
x2 = input("Enter second number: ")

"""Question 1: Print the values of the two variables? As you might have noticed, data type of x1 and x2 is string. Even though we entered integers, the input function converts them into string by default. Now we do some data type conversion from string to integers:"""

print(f"\nQuestion 1:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")

# Convert strings to integers
x1 = int(x1)
x2 = int(x2)

"""Question 2: What is the data type of x1 and x2? Now perform simple comparisons between x1 and x2:

Check if the two variables are equal?

Check if x1 is greater than x2?

Check if x2 is greater than x1?

Check if x1 is not equal to x2?

Store the difference between the two variables x1 and x2 in another variable x3 (subtract the smaller number from the larger number).

Increment the smaller of the two variables (x1 and x2) with the difference.Use the shorthand addition operator for the same. Again check if x1 and x2 are equal or not?
"""

print(f"\nQuestion 2:")
print(f"Data type of x1: {type(x1)}")  # int
print(f"Data type of x2: {type(x2)}")  # int

# Comparisons
print(f"x1 == x2: {x1 == x2}")  # Check if equal
print(f"x1 > x2: {x1 > x2}")    # Check if x1 greater than x2
print(f"x2 > x1: {x2 > x1}")    # Check if x2 greater than x1
print(f"x1 != x2: {x1 != x2}")  # Check if not equal

# Store difference (subtract smaller from larger)
if x1 > x2:
    x3 = x1 - x2
    smaller = x2
    larger = x1
else:
    x3 = x2 - x1
    smaller = x1
    larger = x2

print(f"Difference (x3): {x3}")

# Increment smaller variable with difference
smaller += x3  # Shorthand addition operator
print(f"After incrementing smaller variable: {smaller}")

# Check if they are equal now
print(f"x1 and x2 are equal now: {x1 == x2}")
# Conclusion: After incrementing the smaller number by the difference, both numbers become equal 